name: Dagger Deno Pipeline
description: Runs a Dagger pipeline written in Deno

inputs:
  source:
    description: 'source file to run as the dagger pipeline'
    required: true
  infisical-token:
    description: 'Infisical API token'
    required: true
  infisical-workspace-id:
    description: 'Infisical workspace id'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v1
    - uses: dagger/dagger-for-github@v5
      env:
        INFISICAL_TOKEN: ${{ inputs.infisical-token }}
        INFISICAL_WORKSPACE_ID: ${{ inputs.infisical-workspace-id }}
      with:
        version: '0.9.6'
        verb: run
        args: deno run -A ${{ inputs.source }}
