name: Ensure checks pass
description: Runs a Check that ensures all checks pass before merging

# TODO? test this script

runs:
  using: 'composite'
  steps:
    - uses: upsidr/merge-gatekeeper@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        self: ensure-checks-pass
