name: stodo
description: Run stodo cli on the current repository

inputs:
  priority:
    description: 'Priority level to filter tasks by'
    default: '8'

# TODO? use the docker image instead

runs:
  using: 'composite'
  steps:
    - uses: denoland/setup-deno@v1
    - name: Run stodo
      shell: bash
      run: deno run --allow-run=rg,git,jq jsr:@michaelmass/stodo/cli search --format pretty -e --jq "[.[] | select(.priority.value >= ${{ inputs.priority }})]"
