name: Build-Dockerhub
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  build-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        id: meta
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.name }}
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/login-action@v3
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v6
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
